
name: python-bootcamp
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.9
    - pip
    - nb_conda
    - jupyter
    - scikit-learn
    - numpy
    - scipy
    - pandas
    - pandas-datareader
    - matplotlib
    - tqdm
    - requests
    - flask
    - pip:
        - kaggle
        # - -r requirements/dev.txt